// Mocks generated by Mockito 5.3.2 from annotations
// in performx/test/0_data/repositories/advice_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:performx/0_data/datasources/advice_remote_datasource.dart'
    as _i5;
import 'package:performx/0_data/models/advice_model.dart' as _i4;
import 'package:performx/0_data/network/network_manager.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeNetworkManager_1 extends _i1.SmartFake
    implements _i3.NetworkManager {
  _FakeNetworkManager_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdviceModel_2 extends _i1.SmartFake implements _i4.AdviceModel {
  _FakeAdviceModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdviceRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdviceRemoteDatasourceImpl extends _i1.Mock
    implements _i5.AdviceRemoteDatasourceImpl {
  @override
  _i2.Client get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
        returnValueForMissingStub: _FakeClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Client);
  @override
  _i3.NetworkManager get network => (super.noSuchMethod(
        Invocation.getter(#network),
        returnValue: _FakeNetworkManager_1(
          this,
          Invocation.getter(#network),
        ),
        returnValueForMissingStub: _FakeNetworkManager_1(
          this,
          Invocation.getter(#network),
        ),
      ) as _i3.NetworkManager);
  @override
  set network(_i3.NetworkManager? _network) => super.noSuchMethod(
        Invocation.setter(
          #network,
          _network,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i6.Future<_i4.AdviceModel> getAdvice() => (super.noSuchMethod(
        Invocation.method(
          #getAdvice,
          [],
        ),
        returnValue: _i6.Future<_i4.AdviceModel>.value(_FakeAdviceModel_2(
          this,
          Invocation.method(
            #getAdvice,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.AdviceModel>.value(_FakeAdviceModel_2(
          this,
          Invocation.method(
            #getAdvice,
            [],
          ),
        )),
      ) as _i6.Future<_i4.AdviceModel>);
}
